name = "rf4-worker"
compatibility_date = "2025-07-01"

[[d1_databases]]
binding = "DB"
database_name = "rf4"
database_id = "bead5b3b-5a98-4fd3-82fa-c63115544ccd"
migrations_dir = "./migrations"

[dev]
port = 8787

[pages]
build_command = "npm run build"
dest_dir = "dist"