-- Migration: Insert batch 23

BEGIN TRANSACTION;

INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', '【停产】Turion SW 30000 7-Years', 0, 128.5, 36.3);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Velara 1000', 7.74, 4.8, 1749.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Velara 3000', 30.55, 12.7, 1949.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Velara 6000', 38.98, 14.5, 2549.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Velara 8000', 41.89, 17.5, 5498.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Velara 6000 Mystique', 0, 38.98, 14.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Velara 8000 Mystique', 0, 41.78, 17.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', '【停产】Venga 6000', 69.66, 22.6, 18790.96);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', '【停产】Venga 8000', 83.98, 27.2, 23001.67);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', '【停产】Venga 10000', 99, 31.7, 32721.57);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga MMXXV 10000', 0, 111.1, 31.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Black 6000', 0, 69.66, 22.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Black 8000', 0, 83.98, 27.2);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Black 10000', 0, 99, 31.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga II 6000', 71.2, 22.7, 18899.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga II 8000 SHS', 80.25, 30, 26899.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga II 10000', 108.31, 32.7, 34499.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga II 30000', 144.12, 34.9, 48499.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Platinum 6000', 0, 69.66, 22.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Platinum 8000', 0, 83.98, 27.2);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Platinum 10000', 0, 99, 31.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga 10000 Final', 0, 99, 31.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Classic 6000', 69.66, 22.6, 18790.96);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga Classic 10000', 99, 31.7, 32721.57);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'VengaⅡ30000 First Edition', 0, 158.06, 34.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Z-Series 2 10S', 7.88, 6, 3597.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Z-Series 2 20S', 16.45, 8.2, 3897.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Z-Series 2 30S', 22.97, 15.7, 3897.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Z-Series 2 40S', 28.18, 15.7, 3997.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Z-Series 2 60S', 45.1, 17.7, 5697.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Horizon III 1000S', 8.27, 4.6, 1099.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Horizon III 2000S', 12, 5.4, 1299.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Horizon III 3000S', 24.9, 12, 1699.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Horizon III 6000S', 38.22, 15.6, 3998.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Tagara II 3000 SHS', 39.76, 16.3, 4998.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Tagara II 6000', 45.89, 18.1, 6299.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Tagara II 8000', 57.06, 22.6, 14655.3);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Tagara II 10000', 62.45, 26.3, 21871.87);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Olaf SP 10', 16.98, 6.7, 4498.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Olaf SP 20', 24.78, 8.9, 5698.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Olaf SP 30', 40.9, 17.6, 7398.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Olaf SP 60', 51.5, 18.6, 7899.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Olaf Stark SP-SWG 100', 71.78, 28.2, 23898.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Bestia II 1000 SHS', 11.41, 8.6, 7899.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Bestia II 2000 SHS', 24.25, 10.8, 13499.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Bestia II 3000 SHS', 43.84, 17.2, 7998.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Bestia II 6000 SHS', 54.6, 19.9, 9488.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Bestia II 8000 SHS', 66.7, 24.5, 16603.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga II 10000 Super 9', 0, 108.3, 34);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('渔轮', 'Venga II 30000 Super 9', 0, 144, 36.7);

COMMIT;
