-- Migration: Insert batch 15

BEGIN TRANSACTION;

INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Persey Spod 3.5LB', 0, 25.2, 680.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Mechta Spod 3.5LB', 0, 35, 839.79);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fortuna Spod 3LB', 0, 35.5, 1037.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fortuna Spod 4.5LB', 0, 52.2, 1037.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dominator Spod 3LB', 0, 48.5, 3292.43);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dominator Spod 4.5LB', 0, 52.5, 3292.43);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Atlas Spod 3.0LB', 0, 55.1, 4605.51);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Atlas Spod 5.0LB', 0, 62, 4605.51);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fortuna Marker 12 3LB', 0, 17.5, 1037.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fortuna Marker 13 4LB', 0, 17.5, 1037.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dominator Marker 3LB', 0, 19.8, 3135.65);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dominator Marker 4LB', 0, 20.7, 3135.65);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dominator Marker 5LB', 0, 21.7, 3135.65);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Atlas Marker 3.0LB', 0, 16.8, 4605.51);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Atlas Marker 4.0LB', 0, 18.7, 4605.51);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Atlas Marker 5.0LB', 0, 19.5, 4605.51);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Saltmaster- Fjord Ultra 88', 0, 25.4, 2399.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Saltmaster- Fjord  88', 0, 28.5, 2599.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Saltmaster- Offshore 88', 0, 38.2, 3498.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Saltmaster- Inshore 92', 0, 33, 2898.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', '7 Seas - 80-30140', 0, 36.3, 3898.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', '7 Seas - 80-120420', 0, 52.3, 4597.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', '7 Seas - 88-50190', 0, 41.3, 4198.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', '7 Seas - 88-120420', 0, 54, 4897.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Ocean Queen 86-50150', 0, 48.2, 5397.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Ocean Queen 86-100300', 0, 61.1, 6197.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Ocean Queen 86-160420', 0, 68.2, 6695.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'poseidon Jig&pilker  82-30130', 0, 45.5, 7498.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'poseidon Jig&pilker 92-40190', 0, 56.4, 8397.3);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'poseidon Jig&pilker 92-80210', 0, 75.3, 9897.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Poseidon Sensi 80-20130', 0, 49.2, 8898.7);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Poseidon Sensi 88-50190', 0, 63.7, 9497.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Poseidon Mega Jig 60260', 0, 88.4, 16899.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Poseidon Mega Pirk 90340', 0, 88.1, 16899.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fjordmaster 70-012', 0, 40.2, 3898.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fjordmaster 70-020', 0, 43.6, 4193.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fjordmaster 70-030', 0, 46.1, 4498.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Fjordmaster 70-050', 0, 48, 4698.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dual Strike 60-040', 0, 59.2, 6298.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dual Strike 70-015', 0, 55, 5897.4);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dual Strike 70-025', 0, 57, 6198.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Dual Strike 70-040', 0, 62, 6798.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Coast Runner 70-025', 0, 76, 7896.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Coast Runner  70-040', 0, 78.3, 8296.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Coast Runner  70-050', 0, 83.1, 8698.9);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Nordmaster 70-030', 0, 95, 9796.8);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Tristar Deep Jig 68-020', 0, 107.5, 12398.6);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Tristar Deep Jig 68-030', 0, 115.4, 13196.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Tristar Deep Jig 68-050', 0, 128.2, 14896.5);
INSERT OR IGNORE INTO equipment (equipmentType, equipmentName, lockTension, panelTension, price) VALUES ('鱼竿', 'Tristar Deep Jig 78-030', 0, 119.3, 13896.5);

COMMIT;
